### ISSUE TITLE
trakt.tv userscript returns empty results

### ISSUE THREAD

**Issue by Kenifornication** [mationic/userscripts#3]
the trakt.tv userscript seems to be broken for some time now, could you please look into it? thank you

**Comment by mationic** [comment]
omdbapi.com went private and a paid subscription is required now. Even if I would pay, my api key would be public (in the script) for everyone to steal, so that's not really an option. I haven't found an alternative yet, sorry.

**Comment by Kenifornication** [comment]
Yeah I guess you're right, that wouldn't be ideal. I guess the only solution would be either make the users input their own keys (1$ a month is nothing) or make the requests go through an intermediary, like a hosted PHP script or something, which would be even more costly (unless you've already got somewhere to put it online).

In any case, I just wanna thank you for the script, been very helpful for me.

EDIT: tried it now with a key and it seems to make it faster, and the sorting is sorted (was on an earlier version), thank you for that
