### ISSUE TITLE
Top Comments Preview appears above expando

### ISSUE THREAD

**Issue by mruac** [mationic/userscripts#4]
Sorry to resurrect an old userscript (how old is old?) but in the past couple of months Reddit has changed somehow and the comments preview has started to appear _above_ the expando (image/self-text) and this confuses me when I browse through my frontpage.

I normally read my frontpage as Title > Content > Comments (hopefully funny and interesting ones!) so I don't have to individually open each page just to read the comments. However with the new set up (Title > Comments > Content) it keeps disorienting me, as my mind is going "where is the content??" then realising it's after the comments preview.

Attached is an example of the weird layout that I'm experiencing.
![screen shot 2017-07-28 at 8 16 21 pm](https://user-images.githubusercontent.com/19784752/28715158-effc93fc-73d5-11e7-821c-e9f1def7e274.png)

**Comment by mationic** [comment]
You're right. I'm going to look into that the next days.

**Comment by mationic** [comment]
fixed
